### ISSUE TITLE
glyph get cut-off on the top/bottom in terminal

### ISSUE THREAD

**Issue by rtgiskard** [jesusmgg/comic-shanns-mono#5]
I'm using foot terminal with archlinux, with font comic mono, the glyph is lilkely to be cut off, here is the [report](https://codeberg.org/dnkl/foot/issues/1443), looks like the issue is related to font.

The font used in the report is [comic-mono-font](https://github.com/dtinth/comic-mono-font), which is related but not this one, after search for a while, I find this active fork and try to switch to this one. this is a comparison of the font effect.

![L_this_R_comic_mono](https://github.com/jesusmgg/comic-shanns-mono/assets/34635040/65aeaadf-ce01-4474-9288-abf42be2decf)

the old comic-mono (on the right) is more like to be cut off more at the top, but it's more clear with small size.
this font is also cut off but is slightly better, here is it in a larger size, which you can tell the difference:

![截图 2023-07-29 20-46-14](https://github.com/jesusmgg/comic-shanns-mono/assets/34635040/8352fd30-d5e9-4b12-8337-aad91288b283)

And for unicode like this, it will be very obvious:

```
echo  Î Ñ
```
the two comic fonts all loose the top part like this:
![截图 2023-07-29 20-56-21](https://github.com/jesusmgg/comic-shanns-mono/assets/34635040/58bd00b3-f99f-4b2d-b6a2-416082925277)

another font [lxgw-wenkai](https://github.com/lxgw/LxgwWenKai) looks well:

![截图 2023-07-29 20-56-29](https://github.com/jesusmgg/comic-shanns-mono/assets/34635040/94eec155-6eb9-433a-a850-4f2af67bd3da)

As I have no experience with font edition, is there any option to adjust the font to make sure the font is more standard so it will not be cut-off and loose info? And is it possible to convert with a [similar script](https://github.com/dtinth/comic-mono-font/blob/master/generate.py) to make the font more clear with a small size(like 12pt or about 14px) in terminal?

**Comment by rtgiskard** [comment]
Here is comparison for the glyphs of the two font with fontconfig, both font hold the right glyphs, but the glyphs in comic is much higher

![截图 2023-07-29 21-17-54](https://github.com/jesusmgg/comic-shanns-mono/assets/34635040/e0be4b04-483e-41a0-84cc-c98e592486be)

**Comment by Mikaela** [comment]
I seem to have opened a duplicate a couple of days ago #6 and it turned out to be a foot issue after all which is fixed in git.

Workaround: `line-height=15` at least with font size 12.

- https://codeberg.org/dnkl/foot/issues/1511
- https://codeberg.org/dnkl/foot/pulls/1513

**Comment by rtgiskard** [comment]
Thanks for the note!
